import { encode } from '@toon-format/toon'

const fmt = (n) => n.toLocaleString('en-US')
const pct = (n) => `${n}%`

// Rows for TOON/JSON: flat, machine-usable, failures included with ok:false.
export function toRows(results) {
  return results.map((r) =>
    r.ok
      ? { name: r.name, ok: true, baseline: r.baselineTokens, candidate: r.candidateTokens, saved: pct(r.savedPct), baselineMs: r.baselineMs, candidateMs: r.candidateMs }
      : { name: r.name, ok: false, error: r.error })
}

export const toToon = (results, agg) => encode({ summary: agg, scenarios: toRows(results) }, { delimiter: ',' })
export const toJson = (results, agg) => JSON.stringify({ summary: agg, scenarios: toRows(results) })

export function toTable(results, agg, { color = process.stdout.isTTY } = {}) {
  const c = (code, s) => (color ? `\x1b[${code}m${s}\x1b[0m` : s)
  const rows = results.map((r) => ({
    name: r.name,
    base: r.ok ? fmt(r.baselineTokens) : '—',
    cand: r.ok ? fmt(r.candidateTokens) : '—',
    saved: r.ok ? pct(r.savedPct) : c('31', 'FAIL'),
    note: r.ok ? '' : r.error,
  }))
  const w = (k, min) => Math.max(min, ...rows.map((x) => x[k].length))
  const nw = w('name', 8); const bw = w('base', 8); const cw = w('cand', 9); const sw = w('saved', 5)
  const lines = [c('2', `  ${'SCENARIO'.padEnd(nw)}  ${'BASELINE'.padStart(bw)}  ${'CANDIDATE'.padStart(cw)}  ${'SAVED'.padStart(sw)}`)]
  for (const x of rows) {
    const dot = x.note ? c('31', '○') : c('32', '●')
    lines.push(`${dot} ${x.name.padEnd(nw)}  ${x.base.padStart(bw)}  ${x.cand.padStart(cw)}  ${x.saved.padStart(sw)}${x.note ? '  ' + x.note : ''}`)
  }
  lines.push(c('2', `  ${'—'.repeat(nw + bw + cw + sw + 8)}`))
  lines.push(`  ${'TOTAL'.padEnd(nw)}  ${fmt(agg.baselineTokens).padStart(bw)}  ${fmt(agg.candidateTokens).padStart(cw)}  ${c('1', pct(agg.savedPct).padStart(sw))}`)
  return lines.join('\n')
}

export function toMarkdown(results, agg, enc) {
  const lines = [
    `# bench results`,
    '',
    `Token A/B: baseline vs candidate, counted with gpt-tokenizer (${enc}). `
      + `${agg.measured}/${agg.scenarios} scenarios measured${agg.failed ? `, ${agg.failed} failed` : ''}.`,
    '',
    `| Scenario | baseline | candidate | saved |`,
    `|---|--:|--:|--:|`,
  ]
  for (const r of results) {
    lines.push(r.ok
      ? `| ${r.name} | ${fmt(r.baselineTokens)} | ${fmt(r.candidateTokens)} | ${pct(r.savedPct)} |`
      : `| ${r.name} | — | — | **failed: ${r.error}** |`)
  }
  lines.push(`| **Total** | **${fmt(agg.baselineTokens)}** | **${fmt(agg.candidateTokens)}** | **${pct(agg.savedPct)}** |`)
  lines.push('', `*Generated by \`bench\`.*`)
  return lines.join('\n') + '\n'
}
